name: Optimize Images
on:
  push:
    paths: ['assets/img/**']
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: calibreapp/image-actions@main
        with:
          compressOnly: true
