name: Link Check
on:
  push:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --accept 200,206,429 --exclude-mail --timeout 20s .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
